BEGIN;

CREATE TABLE IF NOT EXISTS treatment_procedures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id bigint NOT NULL,
    procedure_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(38, 2) NOT NULL,
    note text
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_treatment_procedures_treatment') THEN
        ALTER TABLE treatment_procedures
            ADD CONSTRAINT fk_treatment_procedures_treatment
            FOREIGN KEY (treatment_id) REFERENCES treatments(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_treatment_procedures_procedure') THEN
        ALTER TABLE treatment_procedures
            ADD CONSTRAINT fk_treatment_procedures_procedure
            FOREIGN KEY (procedure_id) REFERENCES procedures(id);
    END IF;
END $$;

ALTER TABLE prescriptions DROP COLUMN IF EXISTS patient_id CASCADE;
ALTER TABLE prescriptions DROP COLUMN IF EXISTS dentist_id CASCADE;
ALTER TABLE prescriptions DROP COLUMN IF EXISTS medical_record_id CASCADE;

DROP TABLE IF EXISTS medical_record_procedures CASCADE;
DROP TABLE IF EXISTS medical_records CASCADE;

DELETE FROM sequences WHERE name IN ('MEDICAL_RECORD', 'MEDICAL_REPORT');

COMMIT;
