BEGIN;

CREATE TABLE IF NOT EXISTS treatments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis text,
    note text,
    treatment_date timestamp without time zone,
    status varchar(255) NOT NULL DEFAULT 'IN_PROGRESS',
    patient_id bigint NOT NULL,
    appointment_id bigint UNIQUE,
    doctor_id bigint,
    deleted_at timestamp with time zone,
    version bigint DEFAULT 0,
    created_at timestamp with time zone,
    modified_at timestamp with time zone
);

ALTER TABLE treatments ADD COLUMN IF NOT EXISTS diagnosis text;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS treatment_date timestamp without time zone;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS status varchar(255) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS patient_id bigint;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS appointment_id bigint;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS doctor_id bigint;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS version bigint DEFAULT 0;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS modified_at timestamp with time zone;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_treatments_patient') THEN
        ALTER TABLE treatments ADD CONSTRAINT fk_treatments_patient FOREIGN KEY (patient_id) REFERENCES patients(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_treatments_appointment') THEN
        ALTER TABLE treatments ADD CONSTRAINT fk_treatments_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_treatments_doctor') THEN
        ALTER TABLE treatments ADD CONSTRAINT fk_treatments_doctor FOREIGN KEY (doctor_id) REFERENCES staffs(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_treatments_appointment') THEN
        ALTER TABLE treatments ADD CONSTRAINT uk_treatments_appointment UNIQUE (appointment_id);
    END IF;
END $$;

ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS treatment_id bigint;
ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS doctor_id bigint;
ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS prescribed_at timestamp without time zone;
ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS advice text;
ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS re_examination_date date;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_prescriptions_treatment') THEN
        ALTER TABLE prescriptions ADD CONSTRAINT fk_prescriptions_treatment FOREIGN KEY (treatment_id) REFERENCES treatments(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_prescriptions_doctor') THEN
        ALTER TABLE prescriptions ADD CONSTRAINT fk_prescriptions_doctor FOREIGN KEY (doctor_id) REFERENCES staffs(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_prescriptions_treatment') THEN
        ALTER TABLE prescriptions ADD CONSTRAINT uk_prescriptions_treatment UNIQUE (treatment_id);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.prescription_medicines') IS NOT NULL
       AND to_regclass('public.prescription_items') IS NULL THEN
        ALTER TABLE prescription_medicines RENAME TO prescription_items;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS prescription_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id bigint NOT NULL,
    medicine_id bigint NOT NULL,
    dosage varchar(255),
    frequency varchar(255),
    duration varchar(255),
    quantity integer,
    instruction text,
    created_at timestamp with time zone,
    modified_at timestamp with time zone
);

ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS prescription_id bigint;
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS medicine_id bigint;
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS dosage varchar(255);
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS frequency varchar(255);
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS duration varchar(255);
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS quantity integer;
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS instruction text;
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE prescription_items ADD COLUMN IF NOT EXISTS modified_at timestamp with time zone;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_prescription_items_prescription') THEN
        ALTER TABLE prescription_items ADD CONSTRAINT fk_prescription_items_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_prescription_items_medicine') THEN
        ALTER TABLE prescription_items ADD CONSTRAINT fk_prescription_items_medicine FOREIGN KEY (medicine_id) REFERENCES medicines(id);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.prescription_medicines') IS NOT NULL THEN
        INSERT INTO prescription_items (id, prescription_id, medicine_id, dosage, quantity, instruction)
        SELECT pm.id, pm.prescription_id, pm.medicine_id, pm.dosage, pm.quantity, pm.instruction
        FROM prescription_medicines pm
        ON CONFLICT DO NOTHING;

        DROP TABLE prescription_medicines;
    END IF;
END $$;

DELETE FROM role_permissions
WHERE permission_id IN (
    SELECT pe.id
    FROM permissions pe
    JOIN pages p ON p.id = pe.page_id
    WHERE p.code = 'INVOICE'
);
DELETE FROM permissions
WHERE page_id IN (SELECT id FROM pages WHERE code = 'INVOICE');
DELETE FROM pages WHERE code = 'INVOICE';

ALTER TABLE pages DROP CONSTRAINT IF EXISTS pages_code_check;
ALTER TABLE pages ADD CONSTRAINT pages_code_check
    CHECK ((code)::text = ANY (ARRAY[
        'PATIENT'::text,
        'STAFF'::text,
        'APPOINTMENT'::text,
        'EXAMINATION'::text,
        'MEDICINE'::text,
        'PRESCRIPTION'::text,
        'TREATMENT'::text,
        'PROCEDURE'::text,
        'USER'::text
    ]));

INSERT INTO pages (code, name) VALUES ('TREATMENT', 'Điều trị') ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (page_id, action_id)
SELECT p.id, a.id FROM pages p, actions a
WHERE p.code = 'TREATMENT' AND a.code = 'VIEW'
ON CONFLICT ON CONSTRAINT uk_page_action DO NOTHING;

INSERT INTO permissions (page_id, action_id)
SELECT p.id, a.id FROM pages p, actions a
WHERE p.code = 'TREATMENT' AND a.code = 'CREATE'
ON CONFLICT ON CONSTRAINT uk_page_action DO NOTHING;

INSERT INTO permissions (page_id, action_id)
SELECT p.id, a.id FROM pages p, actions a
WHERE p.code = 'TREATMENT' AND a.code = 'UPDATE'
ON CONFLICT ON CONSTRAINT uk_page_action DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, pe.id
FROM roles r
JOIN permissions pe ON TRUE
JOIN pages p ON p.id = pe.page_id
JOIN actions a ON a.id = pe.action_id
WHERE r.name IN ('Admin', 'Quản lý', 'Bác sĩ')
  AND p.code = 'TREATMENT'
  AND a.code IN ('VIEW', 'CREATE', 'UPDATE')
  AND NOT EXISTS (
      SELECT 1 FROM role_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = pe.id
  );

COMMIT;
